apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: mesh-test-app
  namespace: mesh-test

resources:
  # Core application components
  - base.yaml
  - redis.yaml
  
  # Flagger progressive delivery
  - canary.yaml
  - loadtester.yaml
  
  # Linkerd + Prometheus integration  
  - linkerd-metric-templates.yaml
  - linkerd-podmonitor-debug.yaml