apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-prices-gather
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: quant-services
  chart:
    spec:
      chart: ./charts/external-prices-gather
      sourceRef:
        kind: GitRepository
        name: quant-services
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: qs-common-config
    namespace: quant-services
    valuesKey: values.yaml
  values:
    image:
      name: external-prices-gather
      tag: 1.0.0
