---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# HelmReleases for quant-services
# These are managed in the consuming repository so they can reference
# the hashed ConfigMap names correctly

resources:
  - adh-consumer.yaml
  - betticker-ws.yaml
  - dash-auth.yaml
  - dash-ws.yaml
  - external-prices-gather.yaml
  - nba-livescores.yaml
  - news-gather.yaml
  - rapid-pini-feeder.yaml
  - rw-proj-min-store.yaml
  - rw-proj-min.yaml
  - unabated-news-feeder.yaml
  - wnba-reports.yaml

# Name reference configuration handled at parent level