---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qs-common-config
  namespace: quant-services
data:
  # Image registry configuration for quant-services
  image.registry: "docker-registry.dev-lab-registry.svc.cluster.local:5000"
  image.repository: ""

  # Google client config
  env.GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID'
  env.GOOGLE_CLIENT_SECRET: 'GOOGLE_CLIENT_SECRET'
  
  # Kafka configuration
  env.ADH_KAFKA_BOOTSTRAP_SERVERS: 'ADH_KAFKA_BOOTSTRAP_SERVERS'
  env.ADH_KAFKA_TOPIC: 'ADH_KAFKA_TOPIC'
  env.KAFKA_BOOTSTRAP_SERVERS: "quant-cluster-kafka-bootstrap.quant-services.svc.cluster.local:9192"

  # Clickhouse configuration
  env.CLICKHOUSE_HOST: clickhouse-clickhouse.clickhouse.svc.cluster.local
  env.CLICKHOUSE_PORT: 8123

  # Redis configuration
  env.REDIS_HOST: "redis-master.quant-services.svc.cluster.local"
  env.REDIS_PORT: 6379
  # Dashboard Redis configuration
  env.DASH_REDIS_HOST: "redis-master.quant-services.svc.cluster.local"
  env.DASH_REDIS_PORT: 6379
