---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quant-services
configMapGenerator:
  - name: qs-common-config
    files:
      - values.yaml=qs-common-values.yaml
# This ensures ConfigMap gets a new name when content changes
configurations:
  - kustomizeconfig.yaml