apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unabated-news-feeder
  namespace: flux-system
spec:
  interval: 1h0m0s
  targetNamespace: quant-services
  chart:
    spec:
      chart: ./charts/unabated-news-feeder
      sourceRef:
        kind: GitRepository
        name: quant-services
        namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: qs-common-config
    valuesKey: values.yaml
  values:
    image:
      name: unabated-news-feeder
      tag: 1.0.0
