---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      version: "0.19.0"
  install:
    crds: CreateReplace  # Add this
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace  # And this
    remediation:
      retries: -1
  timeout: 5m
  interval: 1h0m0s
