apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-lab-service-mesh
  namespace: linkerd

resources:
  - namespaces.yaml
  - repositories.yaml
  - linkerd-cert-manager.yaml
  - linkerd-crds.yaml
  - linkerd-control-plane.yaml
  - linkerd-viz.yaml

secretGenerator:
  - name: linkerd-trust-anchor
    namespace: linkerd
    type: kubernetes.io/tls
    files:
      - tls.crt=ca.crt
      - tls.key=ca.key

patches:
  # Patch Linkerd control plane to wait for linkerd-cert-manager
  - target:
      kind: HelmRelease
      name: linkerd-control-plane
    patch: |-
      - op: add
        path: /spec/dependsOn/-
        value:
          name: linkerd-cert-manager
          namespace: linkerd