apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: dev-lab-monitoring-extras
  namespace: monitoring

resources:
  # Linkerd service mesh monitoring
  - linkerd-servicemonitors.yaml
  - linkerd-podmonitor-simple.yaml
  
  # Flagger progressive delivery monitoring
  - flagger-servicemonitor.yaml
  
  # Grafana dashboards
  - grafana-dashboard-configmap.yaml