---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-lab-repo
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
spec:
  interval: 30s
  ref:
    branch: feature/multiple-canary-apps
  url: ssh://git@github.com/jbotstevens/dev-lab.git
  secretRef:
    name: dev-lab-repo
  ignore: |
    # Ignore non-kubernetes files
    *.md
    # Ignore other directories not related to this cluster
    /scripts/
