#!/bin/bash

# Configure containerd for insecure registry access on all worker nodes
# This script applies the complete containerd configuration that enables
# HTTP access to the dev-lab-control-plane:5000 registry without TLS.
# 
# This solves the "http: server gave HTTP response to HTTPS client" error
# that prevents pods from pulling images from the local registry.

echo "Configuring containerd for insecure registry access..."

# Function to configure containerd on a node
configure_node() {
    local node_name=$1
    echo "Configuring $node_name..."
    
    docker exec "$node_name" sh -c 'cat > /etc/containerd/config.toml << EOF
# explicitly use v2 config format
version = 2

[proxy_plugins]
# fuse-overlayfs is used for rootless
[proxy_plugins."fuse-overlayfs"]
  type = "snapshot"
  address = "/run/containerd-fuse-overlayfs.sock"

[plugins."io.containerd.grpc.v1.cri".containerd]
  # save disk space when using a single snapshotter
  discard_unpacked_layers = true
  # explicitly use default snapshotter so we can sed it in entrypoint
  snapshotter = "overlayfs"
  # explicit default here, as we are configuring it below
  default_runtime_name = "runc"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  # set default runtime handler to v2, which has a per-pod shim
  runtime_type = "io.containerd.runc.v2"
  # Generated by "ctr oci spec" and modified at base container to mount poduct_uuid
  base_runtime_spec = "/etc/containerd/cri-base.json"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
  # use systemd cgroup by default
  SystemdCgroup = true

# Setup a runtime with the magic name ("test-handler") used for Kubernetes
# runtime class tests ...
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler]
  # same settings as runc
  runtime_type = "io.containerd.runc.v2"
  base_runtime_spec = "/etc/containerd/cri-base.json"

[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.test-handler.options]
  SystemdCgroup = true

[plugins."io.containerd.grpc.v1.cri"]
  # use fixed sandbox image
  sandbox_image = "registry.k8s.io/pause:3.7"
  # allow hugepages controller to be missing
  # see https://github.com/containerd/cri/pull/1501
  tolerate_missing_hugepages_controller = true
  # restrict_oom_score_adj needs to be true when running inside UserNS (rootless)
  restrict_oom_score_adj = false

# Registry configuration for insecure HTTP access
[plugins."io.containerd.grpc.v1.cri".registry]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."dev-lab-control-plane:5000"]
      endpoint = ["http://dev-lab-control-plane:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs]
    [plugins."io.containerd.grpc.v1.cri".registry.configs."dev-lab-control-plane:5000".tls]
      insecure_skip_verify = true
    [plugins."io.containerd.grpc.v1.cri".registry.configs."dev-lab-control-plane:5000".transport]
      plain_http = true
EOF'

    # Restart containerd
    docker exec "$node_name" systemctl restart containerd
    
    # Restart kubelet
    docker exec "$node_name" systemctl restart kubelet
    
    echo "✅ Node $node_name configured successfully"
}

# Configure all worker nodes
for node in dev-lab-worker dev-lab-worker2; do
    if docker ps --format "table {{.Names}}" | grep -q "^$node$"; then
        configure_node "$node"
    else
        echo "Node $node not found, skipping..."
    fi
done

echo "🎉 Registry configuration complete!"
echo ""
echo "To verify the configuration works:"
echo "  kubectl delete pod <failing-pod-name> -n quant-services"
echo "  kubectl get pods -n quant-services"
echo ""
echo "The pods should now be able to pull images from dev-lab-control-plane:5000"
