---
image:
  registry: 294159772612.dkr.ecr.eu-west-1.amazonaws.com
  repository: /quant-pricing-console
  pullPolicy: IfNotPresent
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceAccount:
  create: true
  annotations: {}
podAnnotations:
  linkerd.io/inject: enabled
  config.linkerd.io/skip-outbound-ports: '5000'
